### ISSUE TITLE
"Select all" selects UI text

### ISSUE THREAD

**Issue by Radiergummi** [baianat/align#1]
You can see this with the background color picker. Might apply `user-select: none` to the UI?

**Comment by Abdelrahman3D** [comment]
Thank you for your feedback,
Selecting all UI text is the default browser behavior when pressing `Ctrl + A` / `⌘ + A` .
While the default Align's behavior is to select the current section contents.
this will work fine if you click on select all button, but while the background color picker is open you are no longer focused on the Align's editor so the default browser behavior wont be prevented.
applying `user-select: none` hack will not work in this situation, I think the fix will be to add listener to the document to prevent that action
```js
    document.addEventListener('keydown', (event) => {
      // Do nothing if the event was already processed
      if (event.defaultPrevented) {
        return;
      }
      if (event.ctrlKey || event.metaKey) {
        switch (event.key.toUpperCase()) {
          case 'A':
            event.preventDefault();
          break;
        }
      }
    });
```

**Comment by Radiergummi** [comment]
I actually clicked the select all button, then opened the color picker and all input fields were selected.  
Your fix looks like it'd solve the problem you outlined anyway so it might make sense to implement that nevertheless :smile:
